hm:
  db:
    host: 8.148.27.32 #192.168.88.128 # 修改为你自己的虚拟机IP地址
    pw: admin # 修改为docker中的MySQL密码
    database: hm-trade
  knife4j:
    title: "黑马商城订单管理接口文档"
    description: "黑马商城订单管理接口文档"
    package: com.hmall.trade.controller
