server:
  port: 8080
#spring:
#  main:
#    web-application-type: reactive
#  application:
#    name: gateway
#  cloud:
#    nacos:
#      server-addr: 8.148.27.32:8848
#    gateway: #这样写路由信息是写死的，一旦路由需要变更，则整个网关服务都需要重启，因此需要实现动态路由，即交给nacos进行管理
#      routes: #但是nacos只负责在有更新时进行推送，因此网关路由表的更新需要自己更新
#        - id: item # 路由规则id，自定义，唯一
#          uri: lb://item-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
#          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
#            - Path=/items/**,/search/** # 这里是以请求路径作为判断规则
#        - id: cart
#          uri: lb://cart-service
#          predicates:
#            - Path=/carts/**
#        - id: user
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**,/addresses/**
#        - id: trade
#          uri: lb://trade-service
#          predicates:
#            - Path=/orders/**
#        - id: pay
#          uri: lb://pay-service
#          predicates:
#            - Path=/pay-orders/**
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    exclude-paths:
      - /search/**
      - /users/login
      - /items/**
      - /hi



